<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>VrfInsights.Gui</RootNamespace>
    <AssemblyName>VrfInsights.Gui</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VrfInsights.Pipeline\VrfInsights.Pipeline.csproj" />
  </ItemGroup>

</Project>
